FROM rust:1.27

WORKDIR /usr/src/kubeless
RUN rustup default nightly \
  && rustup update

ENV USER root
CMD ["/usr/src/kubeless/target/debug/kubeless"]
ENV ROCKET_ADDRESS '0.0.0.0'

RUN cargo new kubeless --bin
COPY Cargo.toml .
COPY src ./src/
RUN cargo build
ENV FUNC_PORT 8000
CMD ROCKET_PORT=$FUNC_PORT /usr/src/kubeless/target/debug/kubeless
