FROM rust:1.27

WORKDIR /usr/src/kubeless
RUN rustup default nightly \
  && rustup update
COPY Cargo.toml .
COPY src ./src/

ENV USER root
RUN cargo new kubeless --bin \
  && cargo build


CMD ["/usr/src/kubeless/target/debug/kubeless"]
